/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadBandCpu */

#ifndef _Included_ThreadBandCpu
#define _Included_ThreadBandCpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ThreadBandCpu
 * Method:    bandCpu
 * Signature: (Ljava/lang/Runnable;I)V
 */
JNIEXPORT void JNICALL Java_ThreadBandCpu_bandCpu
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
